import {
  Paper,
  Text,
  Code,
  Stack,
  ScrollArea,
  Group,
  Badge,
} from "@mantine/core";

interface TokenDisplayProps {
  tokens: Array<{
    text: string;
    index: number;
    isGenerated: boolean;
  }>;
  currentStep: number;
}

export function TokenDisplay({ tokens, currentStep }: TokenDisplayProps) {
  return (
    <Paper p="md" radius="md" withBorder style={{ height: "100%" }}>
      <Stack gap="md" h="100%">
        <Group justify="space-between">
          <Text size="lg" fw={600}>
            Generated Text
          </Text>
          <Badge variant="light" size="lg">
            {tokens.length} tokens
          </Badge>
        </Group>

        <ScrollArea h={250} type="auto">
          <Code
            block
            style={{
              fontSize: "16px",
              lineHeight: "1.8",
              padding: "16px",
              minHeight: "200px",
              whiteSpace: "pre-wrap",
              wordBreak: "break-word",
            }}
          >
            {tokens.length === 0 ? (
              <Text c="dimmed" fs="italic">
                Generated text will appear here...
              </Text>
            ) : (
              tokens.map((token, idx) => (
                <span
                  key={idx}
                  style={{
                    backgroundColor: token.isGenerated
                      ? idx === currentStep
                        ? "rgba(64, 192, 87, 0.3)" // Current token - green highlight
                        : "rgba(64, 192, 87, 0.15)" // Generated - light green
                      : "transparent", // Original prompt - no highlight
                    padding: "2px 4px",
                    borderRadius: "3px",
                    transition: "all 0.3s ease",
                    display: "inline",
                    animation:
                      idx === currentStep ? "pulse 0.5s ease-in-out" : "none",
                  }}
                >
                  {token.text}
                </span>
              ))
            )}
          </Code>
        </ScrollArea>

        <Text size="xs" c="dimmed">
          💡 Highlighted tokens are generated by the model. The most recent
          token pulses.
        </Text>
      </Stack>

      <style>{`
        @keyframes pulse {
          0%, 100% {
            transform: scale(1);
            background-color: rgba(64, 192, 87, 0.3);
          }
          50% {
            transform: scale(1.05);
            background-color: rgba(64, 192, 87, 0.6);
          }
        }
      `}</style>
    </Paper>
  );
}
